spring:
  kafka:
    bootstrap-servers: 192.168.0.5:9092
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    ollama:
      base-url: http://192.168.0.8:11434
docuhelper:
  file:
    endpoint: http://localhost:8082

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.bmserver.docuhelperdocumentparser: DEBUG       # ?????? ???? ?? ??