server:
  port: 8084
spring:
  main:
    web-application-type: none
  kafka:
    consumer:
      auto-offset-reset: latest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  ai:
    openai:
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4.1-nano-2025-04-14
